apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: me14server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me14server
  template:
    metadata:
      labels:
        app: me14server
    spec:
      containers:
      - name: me14server
        image: mntiot.azurecr.io/me14server:v1.0.1
        ports:
        - containerPort: 5000        
      imagePullSecrets:
      - name: mntiot
---
apiVersion: v1
kind: Service
metadata:
  name: me14server
spec: 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: me14  
  selector:
    app: me14server          