apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-volume-claim 
spec:
  accessModes:
    - ReadOnlyMany  
  resources:
    requests:
      storage: 1Gi
  storageClassName: storageclass-certs