apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-persistence-certs-claim 
spec:
  accessModes:
    - ReadOnlyMany  
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefilestorage