apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-volume
  labels: 
    storage: slow
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  storageClassName: storageclass-certs
  azureFile:
    secretName: certs-volume-secret
    shareName: certs
    readOnly: true