apiVersion: v1
kind: Secret
metadata:
  name: static-persistence-certs-secret
type: Opaque
data:
  azurestorageaccountname: [base64encodedStorageAccountName]
  azurestorageaccountkey: [base64encodedStorageAccountKey]